version: "3.8"

networks:
  wedding_basic:

services:
  invitation:
    container_name: invitation
    hostname: invitation
    image: "registry-intl.cn-hongkong.aliyuncs.com/happywifehappylife/wedding-invitation:v7"
    restart: unless-stopped
    ports:
    - 3000:3000
    networks:
    - wedding_basic
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped
    ports:
    - 27017:27017
    volumes:
    - wedding_data:/data/db
    networks:
    - wedding_basic
  nginx:
    image: nginx:mainline-alpine3.18
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
    - wedding_basic
    external_links:
    - invitation
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
    - wedding_basic

volumes:
  wedding_data: